
manual = [
    "adult video",
    "porn",
]

# list of video titles to prevent matic mode from queueing
magic_mode = [
    "havana",
    "bts",
    "watch mojo",
    "top 5",
    "top 10",
    "top 12",
    "top 20",
    "top 30",
    "top 50",
    "top 100",
    "top 25",
    "kids react",
    "youtubers react",
    "teens react",
    "life hack",
    "react:",
    "react to",
    "youtubers",
    "elders react",
    "guess that song",
    "celebs react",
    "cats react"
    "s react",
    "lets play",
    "let's play",
    "letz play",
    "lest play",
    "let play"
    "letsplay",
    "reaction",
    "adult video",
    "porn",
    "5 best",
    "10 best",
    "15 best",
    "salvonic",
    "just dance",
    "Look at my Horse, my Horse is Amazing",
    "minutes or less",
    "O Holy Night worst rendition ever FUNNIEST SONG ON EARTH",
    "moana",
    "dwane johnson"
    "x factor",
    "videos",
    "compilation",
    "how to",
    "tutorial",
    "late night",
    "TheFatRat",
    "anime",
    "@",
    "#",
    "banana",
    "the voice",
    "audition",
    "got talent",
    "league of legends",
    "lol",
    "funny",
    "ear rape",
    "!!",
    "!?",
    "??",
    "1 hour",
    "2 hours",
    "3 hours",
    "4 hours",
    "5 hours",
    "6 hours",
    "7 hours",
    "8 hours",
    "9 hours",
    "10 hours",
    "15 hours",
    "20 hours",
    "24 hours",
    "full soundtrack",
    "full ost",
    "b t s"

]
